FROM cuda-jdk17:v1

WORKDIR /usr/src/app
ARG JAR_FILE
ARG UID_GID=1001
ENV UID=${UID_GID}
ENV GID=${UID_GID}
ENV JAVA_OPTS='--add-opens=java.base/java.lang=ALL-UNNAMED \
               --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
               --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
               --add-opens=java.base/java.io=ALL-UNNAMED \
               --add-opens=java.base/java.net=ALL-UNNAMED \
               --add-opens=java.base/java.nio=ALL-UNNAMED \
               --add-opens=java.base/java.util=ALL-UNNAMED \
               --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
               --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
               --add-opens=java.base/sun.nio.ch=ALL-UNNAMED \
               --add-opens=java.base/sun.nio.cs=ALL-UNNAMED \
               --add-opens=java.base/sun.security.action=ALL-UNNAMED \
               --add-opens=java.base/sun.util.calendar=ALL-UNNAMED \
               --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED \
               -Dcom.sun.management.jmxremote=true \
               -Dcom.sun.management.jmxremote.port=1098 \
               -Dcom.sun.management.jmxremote.rmi.port=1098 \
               -Dcom.sun.management.jmxremote.ssl=false \
               -Dcom.sun.management.jmxremote.authenticate=false \
               -Dcom.sun.management.jmxremote.local.only=false \
               -Djava.rmi.server.hostname=localhost'

RUN mkdir -p jars
COPY jars jars

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt install -y python-is-python3 wget curl ca-certificates bash libgomp1 && \
    rm -rf /var/cache/apt/*

RUN mkdir -p /opt/spark/
COPY test_datasets /opt/spark

COPY ${JAR_FILE} ml-service.jar

RUN groupadd --gid $UID appuser && useradd --uid $UID --gid appuser --shell /bin/bash --create-home appuser
RUN chown -R appuser:appuser /home/appuser && chown -R appuser:appuser /usr/src/app

EXPOSE 4040
EXPOSE 1098
EXPOSE 9090
USER $UID
ENTRYPOINT java $JAVA_OPTS -jar ml-service.jar