version: '2'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=5432
      - POSTGRES_SERVICE=postgres
    command: -p 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"
